In [1]:
import numpy as np

# np 쓰기 전에 무조건 해야 되는 거

In [2]:
T = np.array([[1,2,3,4],[1,2,3,4],[1,3,5,7]])
print(T)

# numpy
# np.array([[1,2,3,4],[1,2,3,4],[1,3,5,7]])는 가로 4칸, 세로 3칸 행렬이 나온다.

[[1 2 3 4]
 [1 2 3 4]
 [1 3 5 7]]


In [3]:
Y = np.array([[1,1,2,2],[1,1,3,3]])
V = np.array([[3,3],[1,1],[2,2],[4,4]])
print(Y)
print(V)
print(np.dot(Y, V))

# numpy
# np.dot(Y, V)는 행렬 곱이다.

[[1 1 2 2]
 [1 1 3 3]]
[[3 3]
 [1 1]
 [2 2]
 [4 4]]
[[16 16]
 [22 22]]


In [4]:
I = np.array([[4,5],[6,7],[8,9]])
J = np.array([[6,6],[8,8]])
print(I)
print(J)
print(np.concatenate([I, J]))

# numpy
# np.concatenate([I,J])는 행렬 I 밑에 행렬 J를 이어붙인다.

[[4 5]
 [6 7]
 [8 9]]
[[6 6]
 [8 8]]
[[4 5]
 [6 7]
 [8 9]
 [6 6]
 [8 8]]


In [5]:
H = np.array([[3,5,7],[2,5,7],[1,5,7]])
G = np.array([[10,10,10],[20,20,20]])
F = np.array([[5],[5],[5555]])
print(np.vstack([H, G]))
print(np.hstack([H, F]))

# numpy
# np.vstack([H, G])는 행렬 H 밑에 행렬 G를 이어붙인다.
# np.hstack([H, F])는 행렬 H 오른쪽에 행렬 F를 이어붙인다.

[[ 3  5  7]
 [ 2  5  7]
 [ 1  5  7]
 [10 10 10]
 [20 20 20]]
[[   3    5    7    5]
 [   2    5    7    5]
 [   1    5    7 5555]]
